[project]
name = "baseball-mcp"
version = "0.0.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
    "pybaseball>=2.2.7",
]
